"""add is_admin to users

Revision ID: 74b0abd5a318
Revises: 001
Create Date: 2026-01-18 03:39:18.567581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '74b0abd5a318'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mazes_name'), table_name='mazes')
    op.add_column('sessions', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('sessions_user_id_fkey'), 'sessions', type_='foreignkey')
    op.drop_constraint(op.f('sessions_maze_id_fkey'), 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'sessions', 'mazes', ['maze_id'], ['id'])
    op.drop_column('sessions', 'updated_at')
    op.add_column('submissions', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('submissions', 'code_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.drop_constraint(op.f('submissions_user_id_fkey'), 'submissions', type_='foreignkey')
    op.drop_constraint(op.f('submissions_maze_id_fkey'), 'submissions', type_='foreignkey')
    op.create_foreign_key(None, 'submissions', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'submissions', 'mazes', ['maze_id'], ['id'])
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index(op.f('ix_users_api_key_prefix'), table_name='users')
    op.drop_index(op.f('ix_users_verification_token'), table_name='users')
    op.create_index(op.f('ix_users_api_key_hash'), 'users', ['api_key_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_api_key_hash'), table_name='users')
    op.create_index(op.f('ix_users_verification_token'), 'users', ['verification_token'], unique=True)
    op.create_index(op.f('ix_users_api_key_prefix'), 'users', ['api_key_prefix'], unique=True)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('users', 'is_admin')
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.create_foreign_key(op.f('submissions_maze_id_fkey'), 'submissions', 'mazes', ['maze_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('submissions_user_id_fkey'), 'submissions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('submissions', 'code_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.drop_column('submissions', 'started_at')
    op.add_column('sessions', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.create_foreign_key(op.f('sessions_maze_id_fkey'), 'sessions', 'mazes', ['maze_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('sessions_user_id_fkey'), 'sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('sessions', 'completed_at')
    op.create_index(op.f('ix_mazes_name'), 'mazes', ['name'], unique=True)
    # ### end Alembic commands ###
